waypoint_control_node:
  ros__parameters:
    kp_yaw: 0.6
    kp_dist: 0.75
    max_yaw_thrust: 3.0
    absolute_max_motor_signal: 40.0
    yaw_deadband_deg: 15.0
    dvl_active: false

point_extract:
  ros__parameters:
    look_ahead_pixels: 100
    angle_weight: 0.5

behaviour_node:
  ros__parameters:
    tree_xml_file: "reactive_mission.xml"